### ISSUE TITLE
input on README

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/chuck-max#13]
You asked for input on the updated README.

The README is great. Informative and detailed. The new callback section is impressive and shows this to be an important feature. To be honest though, I don't have a strong enough programming background to understand how to use these yet. I've looked at `test_callback` but I'm not there yet. 

 I have some suggested minor edits. It was easiest to put it into a PR. Just a few text clarifications, and tightening up some wording. (I've done some work in an editor role, so it is hard for me to resist!) 

I added a note about not using `dur` and `time` and to match the type when using number/flonum objects. 

Formatting style - I'm a fan of using headings so I added a few, but you may not want them

You should only accept changes that make sense to you, though. np  if you reject the whole thing!

**Comment by shakfu** [comment]
@HighHarmonics2 

> I have some suggested minor edits. It was easiest to put it into a PR. Just a few text clarifications, and tightening up some wording. (I've done some work in an editor role, so it is hard for me to resist!)

Of course, I welcome feedback for sure. This work is done in my spare time so I can only iterate over things to improve them over time so feedback is alway good even if I end up going in another direction!

**Comment by shakfu** [comment]
I've improved the README further so I'll close this. Thanks for your feedback.
