### ISSUE TITLE
make brew build failed

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/chuck-max#18]
`make brew` failed

intel iMac
macOS: 12.7.4 (Monterey)
brew --version: 4.3.0

ran `rm -f examples/chugins/*.ghug` prior to build 

Build failed message
```
The following build commands failed:
	Ld /Users/one/dev/sound/chuck-max/build/source/projects/chugins/WarpBuf/Release/WarpBuf.chug normal (in target 'WarpBuf' from project 'chuck-max')
(1 failure)
make: *** [brew] Error 65
```

[chuck-max-make-brew-ERROR-5-15-24.txt](https://github.com/shakfu/chuck-max/files/15324211/chuck-max-make-brew-ERROR-5-15-24.txt)

**Comment by HighHarmonics2** [comment]
`make full` also failed 

```
src/libmpg123/check_neon.S:13:2: error: unknown directive .code
 .code 32
 ^
src/libmpg123/check_neon.S:31:2: error: invalid instruction mnemonic 'vorr'
 vorr d0, d0, d0
 ^~~~
src/libmpg123/check_neon.S:32:2: error: invalid instruction mnemonic 'bx'
 bx lr
 ^~
make[1]: *** [src/libmpg123/check_neon.lo] Error 1
make: *** [install_deps] Error 2
```

[chuck-max-make-full-ERROR-5-15-24.txt](https://github.com/shakfu/chuck-max/files/15325065/chuck-max-make-full-ERROR-5-15-24.txt)

**Comment by shakfu** [comment]
> `make brew` failed

Not so far off the end, there's an error while building WarpBuf: `clang: error: no such file or directory: '/usr/local/lib/libsndfile.a'`

If you type `brew install libsndfile` and you can check if this actually installs a static library: `libsndfile.a` by typing 

```bash
cd `brew --prefix libsndfile`
cd lib
ls
```
what is the result of above in command line?

**Comment by shakfu** [comment]
> `make full` also failed

It's failing with libmpg123 which is the only part of this file which I replaced. Let's revert that change and try again.

Find the `sources/scripts/install_deps.sh` file, make a backup of it, then replace it with the attached file, and then  re-run `make file`

[install_deps.sh.zip](https://github.com/shakfu/chuck-max/files/15325644/install_deps.sh.zip)

**Comment by HighHarmonics2** [comment]
I ran `brew install libsndfile` brew says it is already installed and up-to-date.

`/usr/local/opt/libsndfile/lib> ls`

```
cmake
libsndfile.1.dylib
pkgconfig
libsndfile.1.0.37.dylib
libsndfile.dylib
```

It looks like `make` is looking in `/usr/local/lib/`, but brew has it in `/usr/local/opt/`

**Comment by shakfu** [comment]
@HighHarmonics2  I have a fix: just `git pull` to the latest code and do `make nomp3`

This gets you everything except mp3 support which is tricky on older systems. More info later...

Let me know if this works for you.

**Comment by shakfu** [comment]
> I ran `brew install libsndfile` brew says it is already installed and up-to-date.
> 
> `/usr/local/opt/libsndfile/lib> ls`
> 
> ```
> cmake
> libsndfile.1.dylib
> pkgconfig
> libsndfile.1.0.37.dylib
> libsndfile.dylib
> ```

This is what I suspected.  On some earlier version of homebrew, `libsndfile` is not provided in its static form: `libsndfile.a` (which is what we use in chuck-max). This means you will have to build libsndile manually with `make nomp3` as before (i.e. before I added mp3 support).

I know it this is a bit confusing, I will make a table to show variant compatibility relative your macOS platform version which can be found in the 'About this Mac` menu in the top left of your screen or via `xcrun --show-sdk-platform-version` in the command line.

Basically, you are on a Mac intel running on macOS Monterey which is macOS version 12 as per [this list](https://en.wikipedia.org/wiki/MacOS_version_history) 

When you install a new version of macOS or move to a new architecture like Apple Silicon , Apple changes the development environment somewhat with a new version of Xcode and command line utilities, and a new macOS SDK with changes to what this SDK support as well as new security rules...  package managers like homebrew, then have to respond to these change, and sometimes this means a change where they store installed software (like the change from `/usr/local` to `/opt/homebrew` but also how it is supported. These changes are sometime subtle like the one we have in this case.

It's no biggie, just means we have to track these differences and account for them.

**Comment by HighHarmonics2** [comment]
** BUILD SUCCEEDED **

`git pull`
`make nomp3`

It took a really long time, but it worked!

**Comment by HighHarmonics2** [comment]
There was another failure on `make full` and you wanted me to change out `install_deps.sh` -- is that still something I should do? or does `make nomp3` cover that?

**Comment by shakfu** [comment]
Just use nomp3 for now.  I'm testing all the variants using a github workflow and will have a better sense of where the problems are.

**Comment by shakfu** [comment]
Just systematically tested the build variants on macOS 11-14 inclusive with the resulting table in the README. Long story short: fallback to `make nomp3` if `make brew` fails.

<img width="223" alt="macos-variants" src="https://github.com/shakfu/chuck-max/assets/3701918/cdc48487-6ee6-49e4-b14c-5440085fa1a9">
