### ISSUE TITLE
add an attribute to the chuck~ object to make output of param values to console configurable

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/chuck-max#2]
Currently all Max UI objects that input to chuck~ reflect value changes to the console:

```
chuck~ • param carGain: 0.400000
chuck~ • param modIndex: 5000
chuck~ • param modIndex: 5001
```
This is sometimes useful but can be distracting when using chuck debug comments/messages. It is particularly intrusive when sending continuous change values from a slider or scrolling a number value. 

Suggested behavior:
attribute name: paramConsoleOutput
values: 0 / 1
default: 1  (on)
behavior: Max UI objects will only output param values to console when attribute is set to 1.

**Comment by shakfu** [comment]
I've added two flags: 

1. A compile-time `DEBUG` flag, which defaults to `0` to make the console less noisy... and which can be set at compilation to `1` 

2. A runtime-time `c_debug` flag: The DEBUG flag sets the default value of the `c_debug` flag which actually determines if debugging posts are printed to the console or not, such as printing all param changes to the console.

This arrangement provides the most flexibility.

**Comment by HighHarmonics2** [comment]
The runtime flag works as an attribute that can be easily turned on/off from Max - so it makes it very easy to use. Thanks!
