### ISSUE TITLE
Enable stereo output for chuck~

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/chuck-max#3]
Currently the chuck~ object only has one outlet. 

Stereo output is needed so that chuck programs with stereo output such as panning or use of `dac.right` and `dac.left` can be directed to separate outlets in Max.

**Comment by shakfu** [comment]
change the following definitions to 2 to get stereo input and output

```c
#define N_IN_CHANNELS 1
#define N_OUT_CHANNELS 1
```

**Comment by shakfu** [comment]
@HighHarmonics2 

You will find this very amusing, but in trying to get the great [fauck](https://github.com/ccrma/fauck) chugin (faust in chuck) to work nice with chuck-max, I ended up in a situation where chuck~ needed to default to stereo to work nice with this chugin.

This means that we may need to revisit the default to the stereo which I am sure you will be pleased with. 😄
