### ISSUE TITLE
make build failed - error 65 - callback errors 

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/chuck-max#5]
make: *** [native] Error 65
I've tried removing the build folder and running make again. But I get the same error code. 

These look like the most relevant ones from the callback changes: 

```~/chuck-max/source/projects/chuck_tilde/chuck_tilde.cpp:21:14: error: no
      template named 'unordered_map' in namespace 'std'
typedef std::unordered_map<std::string, ck_callback> callback_map;
        ~~~~~^
~/chuck-max/source/projects/chuck_tilde/chuck_tilde.cpp:188:18: error: 
      member reference base type 'callback_map' (aka 'int') is not a structure or union
        x->cb_map.emplace("demo", &cb_demo);
        ~~~~~~~~~^~~~~~~~
~/chuck-max/source/projects/chuck_tilde/chuck_tilde.cpp:573:19: error: 
      member reference base type 'callback_map' (aka 'int') is not a structure or union
    if (!x->cb_map.count(s->s_name)) {
         ~~~~~~~~~^~~~~~
~/chuck-max/source/projects/chuck_tilde/chuck_tilde.cpp:577:17: error: 
      cannot initialize a variable of type 'ck_callback' (aka 'void (*)()') with an lvalue of type 'char'
    ck_callback cb = x->cb_map[s->s_name];
                ^    ~~~~~~~~~~~~~~~~~~~~
~/chuck-max/source/projects/chuck_tilde/chuck_tilde.cpp:589:19: error: 
      member reference base type 'callback_map' (aka 'int') is not a structure or union
    if (!x->cb_map.count(s->s_name)) {
         ~~~~~~~~~^~~~~~
~/chuck-max/source/projects/chuck_tilde/chuck_tilde.cpp:593:17: error: 
      cannot initialize a variable of type 'ck_callback' (aka 'void (*)()') with an lvalue of type 'char'
    ck_callback cb = x->cb_map[s->s_name];
```

I also got these warnings  about Gestalt is deprecated in RtAudio

chuck-max/source/projects/chuck/host_embed/RtAudio/RtAudio.cpp:453:16: warning: 
      'Gestalt' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
    if ((err = Gestalt(gestaltSystemVersion, &systemVersion)) != noErr) goto fail;

**Comment by shakfu** [comment]
@HighHarmonics2 Thanks for the bug report.

It's weird I got none of the reported errors. Nonetheless, I've made some changes (adding headers, strengthening the type of keys for the callback map).

Can you please pull the latest commit and try again after clearing your build directory.

**Comment by shakfu** [comment]
In any case I have moved the  new callback code to the `dev` branch as it could use more testing. I have reverted changes in the main branch.

**Comment by shakfu** [comment]
@HighHarmonics2 
I've retested the callback code in the `dev` repository on my old Mac intel mini and it works for me, which means it works for me on both arm64 (m1) and x86_64 (intel/amd) Mac architectures.

Can you please test the `dev` branch? Just do `git clone -b dev https://github.com/shakfu/chuck-max.git` and `make` to build it.

If you have any errors please report them with what system and os version you are on.

Thanks

**Comment by HighHarmonics2** [comment]
@shakfu
I pulled the main branch and `make` resulted in BUILD SUCCEEDED.  I noticed you also reverted the channels back to one, so I found where there is now, changed it and got another successful build. 

I also tested the `dev` branch. The `make` build succeeded. 

I will look at the callback feature. 

btw: I have an intel iMac w macOS 12.7.2

**Comment by shakfu** [comment]
Thanks @HighHarmonics2 

Glad it worked for you finally.  I will probably reintegrate the callback code at some point. I'd like to write some more tests especially with the new chuck examples. It would be great if you help on this front. Also would like to make some progress on  the windows version when I am close to a windows computer.

**Comment by HighHarmonics2** [comment]
@shakfu 
Sure, I'm happy to contribute any way I can. It looks like what you are asking for is to create a .maxpat file that uses the new chuck files you have in the `examples` dir, and add them to `patchers/tests`. 

You already have `test_global_event.maxpat` so the others would be:

* test-callback.ck
* test-local-event.ck

I can do this. 
But I don't fully understand how callbacks work. In `test-callback.ck` I see the `demo.signal();` line in the `playDrums()` function, but I don't understand the expected behavior. I don't observe any change when I comment this out. Sending a broadcast or signal message from Max still triggers the sample play the same way.

**Comment by shakfu** [comment]
@HighHarmonics2 

Actually what I meant is that if you look at the [examples section chuck site](https://github.com/ccrma/chuck/tree/main/examples) there are a bunch of new examples nicely organized in folders. My ask is if you can find an interesting new example or two and create an max patch out around it.

**Comment by HighHarmonics2** [comment]
ok, got it. You are suggesting that I look at the chuck examples and create max patches that use it. 

I can do this. 

Is the purpose to further test/validate chuck-max - or to illustrate how max can work with chuck? And do you have any specific chuck example files you are interested in?

**Comment by shakfu** [comment]
@HighHarmonics2 

Thanks very much!

I think a couple of demos based on the new set of chuck example  would be great... They needn't be too advanced (like your amazing fm patch on discord :smile: ), just illustrative of what can be done and maybe one of them can replace the somewhat boring default `maxtest.ck` 🙏 

If you don't mind I'm going to close this comment, as I think we should open another issue which is more specific to the topic at hand.
