### ISSUE TITLE
Improved Examples

### ISSUE THREAD

**Issue by shakfu** [shakfu/chuck-max#6]
This issue / topic is for a discussion on how to improve `chuck-max`'s current examples. 

A few ideas:

- Should the current set of examples 
   - incorporate any of the newer or more recent examples from the `chuck` project?
   - be replaced by a smaller set demonstrating chuck-max interaction?
- Should unit-test-like examples be organized separately in a `tests` folder?
- ...

**Comment by HighHarmonics2** [comment]
I think the unit test examples should be considered separate from demonstration examples. It seems to me that the unit tests should be designed to cover a range of chuck code to ensure that it runs successfully in chuck-max. 

I think that demonstration examples should show a range of things that can be done with chuck-max. But to be effective, these may need to have modified `.ck` files - at a minimum to make global variables that can be set in Max. 

I think demonstration patches can draw from any source. Recent examples from chuck would be good. I've been looking through those, but there are so many! It is taking time to single out something to use. Do any of these examples stand out for you?

**Comment by shakfu** [comment]
@HighHarmonics2 thanks for your feedback

> I think the unit test examples should be considered separate from demonstration examples. It seems to me that the unit tests should be designed to cover a range of chuck code to ensure that it runs successfully in chuck-max.

I completely agree.  I was thinking about restructuring the current examples folder and renaming it `resources` and include the following folders:

- `chugins`
- `examples`
- `tests`

> I think that demonstration examples should show a range of things that can be done with chuck-max. But to be effective, these may need to have modified .ck files - at a minimum to make global variables that can be set in Max.

Agree, provided we ensure that each example with global variables can be be opened up by a patch with corresponding controls 

>  think demonstration patches can draw from any source. Recent examples from chuck would be good. I've been looking through those, but there are so many! It is taking time to single out something to use. Do any of these examples stand out for you?

Yes the new chuck examples are great. I haven't been through them all, but I have sample a few new ones and they are very good!

**Comment by shakfu** [comment]
> I was thinking about restructuring the current examples folder and renaming it resources and include the following folders:
> - chugins
> - examples
> - tests

After thinking about this some more, the fixed structure of a Max package constrains things somewhat so the above is better suited for the case where everything is embedded in a macOS bundle:

```bash
chuck~.mxo
└── Contents
    ├── MacOS
    ├── Resources
    │   ├── chugins
    │   ├── examples
    │   └── tests
    └── _CodeSignature
```

The current structure can remain as is with an addition of a `tests` folder in the `examples` folder.

**Comment by HighHarmonics2** [comment]
OK. 

> > I think that demonstration examples should show a range of things that can be done with chuck-max. But to be effective, these may need to have modified .ck files - at a minimum to make global variables that can be set in Max.
> 
> Agree, provided we ensure that each example with global variables can be be opened up by a patch with corresponding controls

Yes, it makes sense that a `myExample.ck` file with global variables should have a corresponding `myExample.maxpat` file - with the same file name. Do you want both files together in the Examples dir? (vs `.maxpat` in the patchers dir)

I will add global variables and may need to make other adjustments. Should I make a new file or just modify the existing  one?

> > think demonstration patches can draw from any source. Recent examples from chuck would be good. I've been looking through those, but there are so many! It is taking time to single out something to use. Do any of these examples stand out for you?
> 
> Yes the new chuck examples are great. I haven't been through them all, but I have sample a few new ones and they are very good!

Are there any specific new examples that stand out that you think would be well suited for chuck-max?

**Comment by shakfu** [comment]
I have always put patchers in the `patchers` folder and code examples
In the `examples` folder because of Max package folder design guidelines. Suggest to follow this, since the corresponding chuck filename is given in any case in each `chuck~` instance in a patcher. 

Please pick examples that resonate with you. I will pick some from my side as well.

**Comment by shakfu** [comment]
@HighHarmonics2 

Please see the new `examples` folder after merging the changes from the `dev` branch. The new examples folder is hierarchical with folders nested up to 3 level deep and more organized. It also includes the following changes in comparison to the chuck examples folder:

- removed

    - `book`, due to its deep directory structure.

- added:

    - `max`, for max specific chuck files

    - `test`, for tests related to `chuck-max`

    - `util`, for misc utilities such as `help.ck` and `status.ck`

    - `chugins`, for additional package-level chugins

Let me know what you think and comments if any with the structure. Of course, the need for good examples mapped to Max controls still remains.

**Comment by HighHarmonics2** [comment]
> Let me know what you think and comments if any with the structure. Of course, the need for good examples mapped to Max controls still remains.

Looks good. 

To use the organization, I will put files in:
- `examples/max` new chuck example code and modifications to existing chuck example files.
- `patchers` for the `.maxpat` files

I have found a few example files to work on for chuck => max:

- `deep/shepard.ck`
- `deep/chant.ck`
- `deep/plu3.ck`

I am also going to add a simplified version of my FM-2Modulators patch with chuck code.

**Comment by shakfu** [comment]
@HighHarmonics2 
> To use the organization, I will put files in:
> 
> * `examples/max` new chuck example code and modifications to existing chuck example files.
> * `patchers` for the `.maxpat` files

Sounds good.

> I have found a few example files to work on for chuck => max:
> 
> * `deep/shepard.ck`
> * `deep/chant.ck`
> * `deep/plu3.ck`
> 
> I am also going to add a simplified version of my FM-2Modulators patch with chuck code.

Perfect!

**Comment by shakfu** [comment]
Given the change that makes it possible to package chuck files with Max patchers files, I think this section is no longer relevant. It's better to keep these together as subfolders in the `contrib` folder which contain the relevant max patcher files, chuck files, etc.. and also a README.md if possible. This is a good way to package related files with `chuck~`
