### ISSUE TITLE
Max patchers need file path changed for chuck~ objects

### ISSUE THREAD

**Issue by HighHarmonics2** [shakfu/chuck-max#9]
With the new file structure under `examples/`, now the `.maxpat` test files don't run. 

For example, `patchers/tests/test_callback.maxpat` has the chuck~ object with this file argument:
`chuck~ test-callback.ck`

Now it needs to be:
`chuck~ test/test-callback.ck`

This is true for the other `.maxpat` files. 

Also it looks like you have changed `maxtest.ck` to `max/test.ck`.

**Comment by shakfu** [comment]
Thanks for raising this issue. I  will fix these to work with the new folder structure in my next commit.
